# IP address to listen on, leave empty to listen on anything
address = ""
port = 80
# Run ident daemon on port 113
identd = true
# Hex encode the users IP and use it as the ident
hexIP = false
# Automatically reply to common CTCP messages
auto_ctcp = true
# Verify the certificate chain presented by the IRC server, if this check fails
# the user will be able to choose to still connect
verify_certificates = true

# Defaults for the client connect form
[defaults]
name = "freenode"
host = "chat.freenode.net"
port = 6697
channels = [
  "#dispatch"
]
server_password = ""
ssl = true
# Only allow a nick to be filled in
readonly = false
# Show server and channel info when readonly is enabled
show_details = false

[https]
enabled = true
port = 443
# Path to your cert and private key if you are not using
# the Let's Encrypt integration
cert = ""
key = ""

[letsencrypt]
# Your domain or subdomain, if not set a certificate will be
# fetched for whatever domain dispatch gets accessed through
domain = ""
# An email address lets you recover your accounts private key
email = ""

# Not implemented
[auth]
# Allow usage without being logged in, all channels and settings get
# transferred when logging in or registering
anonymous = true
# Enable username/password login
login = true
# Enable username/password registration
registration = true

[auth.providers.github]
key = ""
secret = ""

[auth.providers.facebook]
key = ""
secret = ""

[auth.providers.google]
key = ""
secret = ""

[auth.providers.twitter]
key = ""
secret = ""

[dcc]
# Receive files through DCC, the user gets to choose if they want to accept the file,
# the file download then gets proxied to the user
enabled = true

[dcc.autoget]
# Instead of proxying the file download directly to the user, dispatch automatically downloads
# DCC files and sends a download link to the user once its done
enabled = false
# Delete the file after the user has downloaded it once
delete = true
# Delete the file after a certain time period of inactivity, not implemented yet
delete_after = "30m"

[proxy]
# Dispatch will make all outgoing connections through the specified proxy when enabled
enabled = false
protocol = "socks5"
host = "127.0.0.1"
port = 1080
username = ""
password = ""

# HTTP Strict-Transport-Security
[https.hsts]
enabled = false
max_age = 31536000
include_subdomains = false
preload = false

# Add your own HTTP headers to the index page
[headers]
# X-Example = "Rainbows"
